# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Shutdown message format
shutdown-message: "&1[&4ATTENTION&1] &eThe server will &4{shutdowntype} &ein &7{timeleft}&e for {reason}!"

# Default reason if none specified in command
default-reason: "scheduled maintenance"

# Cancel message format
cancel-message: "&1[&4ATTENTION&1] &eThe &4{shutdowntype} &ehas been cancelled!"

# How many seconds before shutdown should we notify? This repeats at specified increment until shutdown or cancelled.
# Example: Shutdown in 60 seconds, if this is set to 10 the plugin will notify a total of 6 times. 
notify-every: 30

# Commands for CONSOLE to perform RIGHT BEFORE the shutdown once the timer hits 0
shutdown-commands:
- kickall
- save-all
