# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Update the server list ping MOTD to show when server is scheduled for shutdown/restart
update-ping-motd: true

# Commands to perform just before the server shuts down
shutdown-commands:
- say Goodbye.
- kickall
