name: ${project.name}
main: ${main.class}
version: ${project.version}
author: BillyGalbreath
description: Notify online players before a server shutdown.
commands:
    shutdown:
        description: Shutdown the server after a delay.
        usage: /<command> [delay | cancel]
        aliases: [stop, restart, reboot]
permissions:
    shutdownnotice.*:
        description: Gives every permission.
        default: false
        children:
            shutdownnotice.command.shutdown:
                description: Allow player to use /shutdown command
                default: op
