name: ${project.name}
main: net.pl3x.bukkit.shutdownnotice.Main
version: ${project.version}
website: ${project.url}
description: Bukkit plugin to control server shutdowns and restarts
author: BillyGalbreath
commands:
  shutdown:
    description: Shuts the server down (or optionally restarts it)
    usage: /<command> [time (reason) | cancel]
    aliases:
    - restart
    - reboot
permissions:
  command.shutdown:
    description: Allows access to shutdown or restart the server.
    default: op
